title: MuSigma
email: mattsicker@apache.org
description: > # this means to ignore newlines until "baseurl:"
  A blog about programming mostly.
  <a rel="me" href="https://infosec.exchange/@sickmatter">Mastodon</a>
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://musigma.blog" # the base hostname & protocol for your site
permalink: /:year/:month/:day/:title:output_ext
author: Matt Sicker
github_username: jvz
exclude: 
  - "CNAME"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "vendor/bundle"
  - ".github"
timezone: "America/Chicago"
encoding: "utf-8"
markdown: kramdown
theme: minima
plugins:
  - jekyll-avatar
  - jekyll-sitemap
